from typing import Any

MOCKED_FORECAST_DATA: dict[str, Any] = {
    "lokasi": {
        "adm1": "32",
        "adm2": "32.16",
        "adm3": "32.16.20",
        "adm4": "32.16.20.2003",
        "provinsi": "Jawa Barat",
        "kotkab": "Bekasi",
        "kecamatan": "Cikarang Pusat",
        "desa": "Pasiranji",
        "lon": 107.2025067024,
        "lat": -6.374008913,
        "timezone": "Asia/Jakarta",
    },
    "data": [
        {
            "lokasi": {
                "adm1": "32",
                "adm2": "32.16",
                "adm3": "32.16.20",
                "adm4": "32.16.20.2003",
                "provinsi": "Jawa Barat",
                "kotkab": "Bekasi",
                "kecamatan": "Cikarang Pusat",
                "desa": "Pasiranji",
                "lon": 107.2025067024,
                "lat": -6.374008913,
                "timezone": "+0700",
                "type": "adm4",
            },
            "cuaca": [
                [
                    {
                        "datetime": "2026-06-16T19:00:00Z",
                        "t": 25,
                        "tcc": 98,
                        "tp": 0,
                        "weather": 3,
                        "weather_desc": "Berawan",
                        "weather_desc_en": "Mostly Cloudy",
                        "wd_deg": 138,
                        "wd": "SE",
                        "wd_to": "NW",
                        "ws": 4.7,
                        "hu": 91,
                        "vs": 7360,
                        "vs_text": "< 8 km",
                        "time_index": "6-7",
                        "analysis_date": "2026-06-16T12:00:00",
                        "image": "https://api-apps.bmkg.go.id/storage/icon/cuaca/berawan-pm.svg",
                        "utc_datetime": "2026-06-16 19:00:00",
                        "local_datetime": "2026-06-17 02:00:00",
                    },
                    {
                        "datetime": "2026-06-16T22:00:00Z",
                        "t": 24,
                        "tcc": 96,
                        "tp": 0,
                        "weather": 3,
                        "weather_desc": "Berawan",
                        "weather_desc_en": "Mostly Cloudy",
                        "wd_deg": 154,
                        "wd": "SE",
                        "wd_to": "NW",
                        "ws": 5.2,
                        "hu": 93,
                        "vs": 7008,
                        "vs_text": "< 8 km",
                        "time_index": "9-10",
                        "analysis_date": "2026-06-16T12:00:00",
                        "image": "https://api-apps.bmkg.go.id/storage/icon/cuaca/berawan-pm.svg",
                        "utc_datetime": "2026-06-16 22:00:00",
                        "local_datetime": "2026-06-17 05:00:00",
                    },
                    {
                        "datetime": "2026-06-17T01:00:00Z",
                        "t": 29,
                        "tcc": 1,
                        "tp": 0,
                        "weather": 0,
                        "weather_desc": "Cerah",
                        "weather_desc_en": "Sunny",
                        "wd_deg": 84,
                        "wd": "NE",
                        "wd_to": "SW",
                        "ws": 7.1,
                        "hu": 67,
                        "vs": 7946,
                        "vs_text": "< 8 km",
                        "time_index": "12-13",
                        "analysis_date": "2026-06-16T12:00:00",
                        "image": "https://api-apps.bmkg.go.id/storage/icon/cuaca/cerah-am.svg",
                        "utc_datetime": "2026-06-17 01:00:00",
                        "local_datetime": "2026-06-17 08:00:00",
                    },
                    {
                        "datetime": "2026-06-17T04:00:00Z",
                        "t": 32,
                        "tcc": 21,
                        "tp": 0,
                        "weather": 1,
                        "weather_desc": "Cerah",
                        "weather_desc_en": "Sunny",
                        "wd_deg": 74,
                        "wd": "NE",
                        "wd_to": "SW",
                        "ws": 11.5,
                        "hu": 53,
                        "vs": 8001,
                        "vs_text": "< 9 km",
                        "time_index": "15-16",
                        "analysis_date": "2026-06-16T12:00:00",
                        "image": "https://api-apps.bmkg.go.id/storage/icon/cuaca/cerah-am.svg",
                        "utc_datetime": "2026-06-17 04:00:00",
                        "local_datetime": "2026-06-17 11:00:00",
                    },
                    {
                        "datetime": "2026-06-17T07:00:00Z",
                        "t": 33,
                        "tcc": 24,
                        "tp": 0,
                        "weather": 1,
                        "weather_desc": "Cerah",
                        "weather_desc_en": "Sunny",
                        "wd_deg": 77,
                        "wd": "NE",
                        "wd_to": "SW",
                        "ws": 8.9,
                        "hu": 51,
                        "vs": 8008,
                        "vs_text": "< 9 km",
                        "time_index": "18-19",
                        "analysis_date": "2026-06-16T12:00:00",
                        "image": "https://api-apps.bmkg.go.id/storage/icon/cuaca/cerah-am.svg",
                        "utc_datetime": "2026-06-17 07:00:00",
                        "local_datetime": "2026-06-17 14:00:00",
                    },
                    {
                        "datetime": "2026-06-17T10:00:00Z",
                        "t": 29,
                        "tcc": 36,
                        "tp": 0.1,
                        "weather": 1,
                        "weather_desc": "Cerah",
                        "weather_desc_en": "Sunny",
                        "wd_deg": 30,
                        "wd": "N",
                        "wd_to": "S",
                        "ws": 6.2,
                        "hu": 71,
                        "vs": 7997,
                        "vs_text": "< 8 km",
                        "time_index": "21-22",
                        "analysis_date": "2026-06-16T12:00:00",
                        "image": "https://api-apps.bmkg.go.id/storage/icon/cuaca/cerah-am.svg",
                        "utc_datetime": "2026-06-17 10:00:00",
                        "local_datetime": "2026-06-17 17:00:00",
                    },
                    {
                        "datetime": "2026-06-17T13:00:00Z",
                        "t": 27,
                        "tcc": 72,
                        "tp": 0,
                        "weather": 2,
                        "weather_desc": "Cerah Berawan",
                        "weather_desc_en": "Partly Cloudy",
                        "wd_deg": 210,
                        "wd": "S",
                        "wd_to": "N",
                        "ws": 3.9,
                        "hu": 84,
                        "vs": 8011,
                        "vs_text": "< 9 km",
                        "time_index": "24-25",
                        "analysis_date": "2026-06-16T12:00:00",
                        "image": "https://api-apps.bmkg.go.id/storage/icon/cuaca/cerah berawan-pm.svg",
                        "utc_datetime": "2026-06-17 13:00:00",
                        "local_datetime": "2026-06-17 20:00:00",
                    },
                    {
                        "datetime": "2026-06-17T16:00:00Z",
                        "t": 25,
                        "tcc": 27,
                        "tp": 0,
                        "weather": 1,
                        "weather_desc": "Cerah",
                        "weather_desc_en": "Sunny",
                        "wd_deg": 169,
                        "wd": "SE",
                        "wd_to": "NW",
                        "ws": 3,
                        "hu": 91,
                        "vs": 6986,
                        "vs_text": "< 7 km",
                        "time_index": "27-28",
                        "analysis_date": "2026-06-16T12:00:00",
                        "image": "https://api-apps.bmkg.go.id/storage/icon/cuaca/cerah-pm.svg",
                        "utc_datetime": "2026-06-17 16:00:00",
                        "local_datetime": "2026-06-17 23:00:00",
                    },
                ],
                [
                    {
                        "datetime": "2026-06-17T19:00:00Z",
                        "t": 24,
                        "tcc": 28,
                        "tp": 0,
                        "weather": 1,
                        "weather_desc": "Cerah",
                        "weather_desc_en": "Sunny",
                        "wd_deg": 169,
                        "wd": "SE",
                        "wd_to": "NW",
                        "ws": 3,
                        "hu": 94,
                        "vs": 6995,
                        "vs_text": "< 7 km",
                        "time_index": "30-31",
                        "analysis_date": "2026-06-16T12:00:00",
                        "image": "https://api-apps.bmkg.go.id/storage/icon/cuaca/cerah-pm.svg",
                        "utc_datetime": "2026-06-17 19:00:00",
                        "local_datetime": "2026-06-18 02:00:00",
                    },
                    {
                        "datetime": "2026-06-17T22:00:00Z",
                        "t": 23,
                        "tcc": 11,
                        "tp": 0,
                        "weather": 1,
                        "weather_desc": "Cerah",
                        "weather_desc_en": "Sunny",
                        "wd_deg": 158,
                        "wd": "SE",
                        "wd_to": "NW",
                        "ws": 4.8,
                        "hu": 94,
                        "vs": 7010,
                        "vs_text": "< 8 km",
                        "time_index": "33-34",
                        "analysis_date": "2026-06-16T12:00:00",
                        "image": "https://api-apps.bmkg.go.id/storage/icon/cuaca/cerah-pm.svg",
                        "utc_datetime": "2026-06-17 22:00:00",
                        "local_datetime": "2026-06-18 05:00:00",
                    },
                    {
                        "datetime": "2026-06-18T01:00:00Z",
                        "t": 29,
                        "tcc": 13,
                        "tp": 0,
                        "weather": 1,
                        "weather_desc": "Cerah",
                        "weather_desc_en": "Sunny",
                        "wd_deg": 100,
                        "wd": "E",
                        "wd_to": "W",
                        "ws": 5.6,
                        "hu": 66,
                        "vs": 7987,
                        "vs_text": "< 8 km",
                        "time_index": "36-37",
                        "analysis_date": "2026-06-16T12:00:00",
                        "image": "https://api-apps.bmkg.go.id/storage/icon/cuaca/cerah-am.svg",
                        "utc_datetime": "2026-06-18 01:00:00",
                        "local_datetime": "2026-06-18 08:00:00",
                    },
                    {
                        "datetime": "2026-06-18T04:00:00Z",
                        "t": 32,
                        "tcc": 31,
                        "tp": 0,
                        "weather": 1,
                        "weather_desc": "Cerah",
                        "weather_desc_en": "Sunny",
                        "wd_deg": 64,
                        "wd": "NE",
                        "wd_to": "SW",
                        "ws": 10.2,
                        "hu": 51,
                        "vs": 8012,
                        "vs_text": "< 9 km",
                        "time_index": "39-40",
                        "analysis_date": "2026-06-16T12:00:00",
                        "image": "https://api-apps.bmkg.go.id/storage/icon/cuaca/cerah-am.svg",
                        "utc_datetime": "2026-06-18 04:00:00",
                        "local_datetime": "2026-06-18 11:00:00",
                    },
                    {
                        "datetime": "2026-06-18T07:00:00Z",
                        "t": 33,
                        "tcc": 36,
                        "tp": 0,
                        "weather": 1,
                        "weather_desc": "Cerah",
                        "weather_desc_en": "Sunny",
                        "wd_deg": 63,
                        "wd": "NE",
                        "wd_to": "SW",
                        "ws": 10.2,
                        "hu": 48,
                        "vs": 7988,
                        "vs_text": "< 8 km",
                        "time_index": "42-43",
                        "analysis_date": "2026-06-16T12:00:00",
                        "image": "https://api-apps.bmkg.go.id/storage/icon/cuaca/cerah-am.svg",
                        "utc_datetime": "2026-06-18 07:00:00",
                        "local_datetime": "2026-06-18 14:00:00",
                    },
                    {
                        "datetime": "2026-06-18T10:00:00Z",
                        "t": 29,
                        "tcc": 4,
                        "tp": 0,
                        "weather": 0,
                        "weather_desc": "Cerah",
                        "weather_desc_en": "Sunny",
                        "wd_deg": 67,
                        "wd": "NE",
                        "wd_to": "SW",
                        "ws": 10.2,
                        "hu": 67,
                        "vs": 8011,
                        "vs_text": "< 9 km",
                        "time_index": "45-46",
                        "analysis_date": "2026-06-16T12:00:00",
                        "image": "https://api-apps.bmkg.go.id/storage/icon/cuaca/cerah-am.svg",
                        "utc_datetime": "2026-06-18 10:00:00",
                        "local_datetime": "2026-06-18 17:00:00",
                    },
                    {
                        "datetime": "2026-06-18T13:00:00Z",
                        "t": 27,
                        "tcc": 12,
                        "tp": 0,
                        "weather": 1,
                        "weather_desc": "Cerah",
                        "weather_desc_en": "Sunny",
                        "wd_deg": 122,
                        "wd": "E",
                        "wd_to": "W",
                        "ws": 4.7,
                        "hu": 81,
                        "vs": 7989,
                        "vs_text": "< 8 km",
                        "time_index": "48-49",
                        "analysis_date": "2026-06-16T12:00:00",
                        "image": "https://api-apps.bmkg.go.id/storage/icon/cuaca/cerah-pm.svg",
                        "utc_datetime": "2026-06-18 13:00:00",
                        "local_datetime": "2026-06-18 20:00:00",
                    },
                    {
                        "datetime": "2026-06-18T16:00:00Z",
                        "t": 26,
                        "tcc": 2,
                        "tp": 0,
                        "weather": 0,
                        "weather_desc": "Cerah",
                        "weather_desc_en": "Sunny",
                        "wd_deg": 148,
                        "wd": "SE",
                        "wd_to": "NW",
                        "ws": 4,
                        "hu": 86,
                        "vs": 8002,
                        "vs_text": "< 9 km",
                        "time_index": "51-52",
                        "analysis_date": "2026-06-16T12:00:00",
                        "image": "https://api-apps.bmkg.go.id/storage/icon/cuaca/cerah-pm.svg",
                        "utc_datetime": "2026-06-18 16:00:00",
                        "local_datetime": "2026-06-18 23:00:00",
                    },
                ],
                [
                    {
                        "datetime": "2026-06-18T19:00:00Z",
                        "t": 24,
                        "tcc": 3,
                        "tp": 0,
                        "weather": 0,
                        "weather_desc": "Cerah",
                        "weather_desc_en": "Sunny",
                        "wd_deg": 114,
                        "wd": "E",
                        "wd_to": "W",
                        "ws": 2.1,
                        "hu": 90,
                        "vs": 7637,
                        "vs_text": "< 8 km",
                        "time_index": "54-55",
                        "analysis_date": "2026-06-16T12:00:00",
                        "image": "https://api-apps.bmkg.go.id/storage/icon/cuaca/cerah-pm.svg",
                        "utc_datetime": "2026-06-18 19:00:00",
                        "local_datetime": "2026-06-19 02:00:00",
                    },
                    {
                        "datetime": "2026-06-18T22:00:00Z",
                        "t": 23,
                        "tcc": 59,
                        "tp": 0,
                        "weather": 1,
                        "weather_desc": "Cerah",
                        "weather_desc_en": "Sunny",
                        "wd_deg": 202,
                        "wd": "S",
                        "wd_to": "N",
                        "ws": 2.9,
                        "hu": 94,
                        "vs": 7005,
                        "vs_text": "< 8 km",
                        "time_index": "57-58",
                        "analysis_date": "2026-06-16T12:00:00",
                        "image": "https://api-apps.bmkg.go.id/storage/icon/cuaca/cerah-pm.svg",
                        "utc_datetime": "2026-06-18 22:00:00",
                        "local_datetime": "2026-06-19 05:00:00",
                    },
                ],
            ],
        }
    ],
}

MOCKED_FORECAST_WITH_ONE_MALFORED_DATA: dict[str, Any] = {
    "lokasi": {
        "adm1": "32",
        "adm2": "32.16",
        "adm3": "32.16.20",
        "adm4": "32.16.20.2003",
        "provinsi": "Jawa Barat",
        "kotkab": "Bekasi",
        "kecamatan": "Cikarang Pusat",
        "desa": "Pasiranji",
        "lon": 107.2025067024,
        "lat": -6.374008913,
        "timezone": "Asia/Jakarta",
    },
    "data": [
        {
            "lokasi": {
                "adm1": "32",
                "adm2": "32.16",
                "adm3": "32.16.20",
                "adm4": "32.16.20.2003",
                "provinsi": "Jawa Barat",
                "kotkab": "Bekasi",
                "kecamatan": "Cikarang Pusat",
                "desa": "Pasiranji",
                "lon": 107.2025067024,
                "lat": -6.374008913,
                "timezone": "+0700",
                "type": "adm4",
            },
            "cuaca": [
                [
                    {
                        "datetime": "2026-06-16T19:00:00Z",
                        "t": 25,
                        "tcc": 98,
                        "tp": 0,
                        "weather": 3,
                        "weather_desc": "Berawan",
                        "weather_desc_en": "Mostly Cloudy",
                        "wd_deg": 138,
                        "wd": "SE",
                        "wd_to": "NW",
                        "ws": 4.7,
                        "hu": 91,
                        "vs": 7360,
                        "vs_text": "< 8 km",
                        "time_index": "6-7",
                        "analysis_date": "2026-06-16T12:00:00",
                        "image": "https://api-apps.bmkg.go.id/storage/icon/cuaca/berawan-pm.svg",
                        "utc_datetime": "2026-06-16 19:00:00",
                        "local_datetime": "2026-06-17 02:00:00",
                    },
                    {
                        "datetime": "2026-06-16T22:00:00Z",
                        "t": 24,
                        "tcc": "malformed",  # <- malformed, should be int
                        "tp": 0,
                        "weather": 3,
                        "weather_desc": "Berawan",
                        "weather_desc_en": "Mostly Cloudy",
                        "wd_deg": 154,
                        "wd": "SE",
                        "wd_to": "NW",
                        "ws": 5.2,
                        "hu": 93,
                        "vs": 7008,
                        "vs_text": "< 8 km",
                        "time_index": "9-10",
                        "analysis_date": "2026-06-16T12:00:00",
                        "image": "https://api-apps.bmkg.go.id/storage/icon/cuaca/berawan-pm.svg",
                        "utc_datetime": "2026-06-16 22:00:00",
                        "local_datetime": "2026-06-17 05:00:00",
                    },
                    {
                        "datetime": "2026-06-17T01:00:00Z",
                        "t": 29,
                        "tcc": 1,
                        "tp": 0,
                        "weather": 0,
                        "weather_desc": "Cerah",
                        "weather_desc_en": "Sunny",
                        "wd_deg": 84,
                        "wd": "NE",
                        "wd_to": "SW",
                        "ws": 7.1,
                        "hu": 67,
                        "vs": 7946,
                        "vs_text": "< 8 km",
                        "time_index": "12-13",
                        "analysis_date": "2026-06-16T12:00:00",
                        "image": "https://api-apps.bmkg.go.id/storage/icon/cuaca/cerah-am.svg",
                        "utc_datetime": "2026-06-17 01:00:00",
                        "local_datetime": "2026-06-17 08:00:00",
                    },
                    {
                        "datetime": "2026-06-17T04:00:00Z",
                        "t": 32,
                        "tcc": 21,
                        "tp": 0,
                        "weather": 1,
                        "weather_desc": "Cerah",
                        "weather_desc_en": "Sunny",
                        "wd_deg": 74,
                        "wd": "NE",
                        "wd_to": "SW",
                        "ws": 11.5,
                        "hu": 53,
                        "vs": 8001,
                        "vs_text": "< 9 km",
                        "time_index": "15-16",
                        "analysis_date": "2026-06-16T12:00:00",
                        "image": "https://api-apps.bmkg.go.id/storage/icon/cuaca/cerah-am.svg",
                        "utc_datetime": "2026-06-17 04:00:00",
                        "local_datetime": "2026-06-17 11:00:00",
                    },
                    {
                        "datetime": "2026-06-17T07:00:00Z",
                        "t": 33,
                        "tcc": 24,
                        "tp": 0,
                        "weather": 1,
                        "weather_desc": "Cerah",
                        "weather_desc_en": "Sunny",
                        "wd_deg": 77,
                        "wd": "NE",
                        "wd_to": "SW",
                        "ws": 8.9,
                        "hu": 51,
                        "vs": 8008,
                        "vs_text": "< 9 km",
                        "time_index": "18-19",
                        "analysis_date": "2026-06-16T12:00:00",
                        "image": "https://api-apps.bmkg.go.id/storage/icon/cuaca/cerah-am.svg",
                        "utc_datetime": "2026-06-17 07:00:00",
                        "local_datetime": "2026-06-17 14:00:00",
                    },
                    {
                        "datetime": "2026-06-17T10:00:00Z",
                        "t": 29,
                        "tcc": 36,
                        "tp": 0.1,
                        "weather": 1,
                        "weather_desc": "Cerah",
                        "weather_desc_en": "Sunny",
                        "wd_deg": 30,
                        "wd": "N",
                        "wd_to": "S",
                        "ws": 6.2,
                        "hu": 71,
                        "vs": 7997,
                        "vs_text": "< 8 km",
                        "time_index": "21-22",
                        "analysis_date": "2026-06-16T12:00:00",
                        "image": "https://api-apps.bmkg.go.id/storage/icon/cuaca/cerah-am.svg",
                        "utc_datetime": "2026-06-17 10:00:00",
                        "local_datetime": "2026-06-17 17:00:00",
                    },
                    {
                        "datetime": "2026-06-17T13:00:00Z",
                        "t": 27,
                        "tcc": 72,
                        "tp": 0,
                        "weather": 2,
                        "weather_desc": "Cerah Berawan",
                        "weather_desc_en": "Partly Cloudy",
                        "wd_deg": 210,
                        "wd": "S",
                        "wd_to": "N",
                        "ws": 3.9,
                        "hu": 84,
                        "vs": 8011,
                        "vs_text": "< 9 km",
                        "time_index": "24-25",
                        "analysis_date": "2026-06-16T12:00:00",
                        "image": "https://api-apps.bmkg.go.id/storage/icon/cuaca/cerah berawan-pm.svg",
                        "utc_datetime": "2026-06-17 13:00:00",
                        "local_datetime": "2026-06-17 20:00:00",
                    },
                    {
                        "datetime": "2026-06-17T16:00:00Z",
                        "t": 25,
                        "tcc": 27,
                        "tp": 0,
                        "weather": 1,
                        "weather_desc": "Cerah",
                        "weather_desc_en": "Sunny",
                        "wd_deg": 169,
                        "wd": "SE",
                        "wd_to": "NW",
                        "ws": 3,
                        "hu": 91,
                        "vs": 6986,
                        "vs_text": "< 7 km",
                        "time_index": "27-28",
                        "analysis_date": "2026-06-16T12:00:00",
                        "image": "https://api-apps.bmkg.go.id/storage/icon/cuaca/cerah-pm.svg",
                        "utc_datetime": "2026-06-17 16:00:00",
                        "local_datetime": "2026-06-17 23:00:00",
                    },
                ],
                [
                    {
                        "datetime": "2026-06-17T19:00:00Z",
                        "t": 24,
                        "tcc": 28,
                        "tp": 0,
                        "weather": 1,
                        "weather_desc": "Cerah",
                        "weather_desc_en": "Sunny",
                        "wd_deg": 169,
                        "wd": "SE",
                        "wd_to": "NW",
                        "ws": 3,
                        "hu": 94,
                        "vs": 6995,
                        "vs_text": "< 7 km",
                        "time_index": "30-31",
                        "analysis_date": "2026-06-16T12:00:00",
                        "image": "https://api-apps.bmkg.go.id/storage/icon/cuaca/cerah-pm.svg",
                        "utc_datetime": "2026-06-17 19:00:00",
                        "local_datetime": "2026-06-18 02:00:00",
                    },
                    {
                        "datetime": "2026-06-17T22:00:00Z",
                        "t": 23,
                        "tcc": 11,
                        "tp": 0,
                        "weather": 1,
                        "weather_desc": "Cerah",
                        "weather_desc_en": "Sunny",
                        "wd_deg": 158,
                        "wd": "SE",
                        "wd_to": "NW",
                        "ws": 4.8,
                        "hu": 94,
                        "vs": 7010,
                        "vs_text": "< 8 km",
                        "time_index": "33-34",
                        "analysis_date": "2026-06-16T12:00:00",
                        "image": "https://api-apps.bmkg.go.id/storage/icon/cuaca/cerah-pm.svg",
                        "utc_datetime": "2026-06-17 22:00:00",
                        "local_datetime": "2026-06-18 05:00:00",
                    },
                    {
                        "datetime": "2026-06-18T01:00:00Z",
                        "t": 29,
                        "tcc": 13,
                        "tp": 0,
                        "weather": 1,
                        "weather_desc": "Cerah",
                        "weather_desc_en": "Sunny",
                        "wd_deg": 100,
                        "wd": "E",
                        "wd_to": "W",
                        "ws": 5.6,
                        "hu": 66,
                        "vs": 7987,
                        "vs_text": "< 8 km",
                        "time_index": "36-37",
                        "analysis_date": "2026-06-16T12:00:00",
                        "image": "https://api-apps.bmkg.go.id/storage/icon/cuaca/cerah-am.svg",
                        "utc_datetime": "2026-06-18 01:00:00",
                        "local_datetime": "2026-06-18 08:00:00",
                    },
                    {
                        "datetime": "2026-06-18T04:00:00Z",
                        "t": 32,
                        "tcc": 31,
                        "tp": 0,
                        "weather": 1,
                        "weather_desc": "Cerah",
                        "weather_desc_en": "Sunny",
                        "wd_deg": 64,
                        "wd": "NE",
                        "wd_to": "SW",
                        "ws": 10.2,
                        "hu": 51,
                        "vs": 8012,
                        "vs_text": "< 9 km",
                        "time_index": "39-40",
                        "analysis_date": "2026-06-16T12:00:00",
                        "image": "https://api-apps.bmkg.go.id/storage/icon/cuaca/cerah-am.svg",
                        "utc_datetime": "2026-06-18 04:00:00",
                        "local_datetime": "2026-06-18 11:00:00",
                    },
                    {
                        "datetime": "2026-06-18T07:00:00Z",
                        "t": 33,
                        "tcc": 36,
                        "tp": 0,
                        "weather": 1,
                        "weather_desc": "Cerah",
                        "weather_desc_en": "Sunny",
                        "wd_deg": 63,
                        "wd": "NE",
                        "wd_to": "SW",
                        "ws": 10.2,
                        "hu": 48,
                        "vs": 7988,
                        "vs_text": "< 8 km",
                        "time_index": "42-43",
                        "analysis_date": "2026-06-16T12:00:00",
                        "image": "https://api-apps.bmkg.go.id/storage/icon/cuaca/cerah-am.svg",
                        "utc_datetime": "2026-06-18 07:00:00",
                        "local_datetime": "2026-06-18 14:00:00",
                    },
                    {
                        "datetime": "2026-06-18T10:00:00Z",
                        "t": 29,
                        "tcc": 4,
                        "tp": 0,
                        "weather": 0,
                        "weather_desc": "Cerah",
                        "weather_desc_en": "Sunny",
                        "wd_deg": 67,
                        "wd": "NE",
                        "wd_to": "SW",
                        "ws": 10.2,
                        "hu": 67,
                        "vs": 8011,
                        "vs_text": "< 9 km",
                        "time_index": "45-46",
                        "analysis_date": "2026-06-16T12:00:00",
                        "image": "https://api-apps.bmkg.go.id/storage/icon/cuaca/cerah-am.svg",
                        "utc_datetime": "2026-06-18 10:00:00",
                        "local_datetime": "2026-06-18 17:00:00",
                    },
                    {
                        "datetime": "2026-06-18T13:00:00Z",
                        "t": 27,
                        "tcc": 12,
                        "tp": 0,
                        "weather": 1,
                        "weather_desc": "Cerah",
                        "weather_desc_en": "Sunny",
                        "wd_deg": 122,
                        "wd": "E",
                        "wd_to": "W",
                        "ws": 4.7,
                        "hu": 81,
                        "vs": 7989,
                        "vs_text": "< 8 km",
                        "time_index": "48-49",
                        "analysis_date": "2026-06-16T12:00:00",
                        "image": "https://api-apps.bmkg.go.id/storage/icon/cuaca/cerah-pm.svg",
                        "utc_datetime": "2026-06-18 13:00:00",
                        "local_datetime": "2026-06-18 20:00:00",
                    },
                    {
                        "datetime": "2026-06-18T16:00:00Z",
                        "t": 26,
                        "tcc": 2,
                        "tp": 0,
                        "weather": 0,
                        "weather_desc": "Cerah",
                        "weather_desc_en": "Sunny",
                        "wd_deg": 148,
                        "wd": "SE",
                        "wd_to": "NW",
                        "ws": 4,
                        "hu": 86,
                        "vs": 8002,
                        "vs_text": "< 9 km",
                        "time_index": "51-52",
                        "analysis_date": "2026-06-16T12:00:00",
                        "image": "https://api-apps.bmkg.go.id/storage/icon/cuaca/cerah-pm.svg",
                        "utc_datetime": "2026-06-18 16:00:00",
                        "local_datetime": "2026-06-18 23:00:00",
                    },
                ],
                [
                    {
                        "datetime": "2026-06-18T19:00:00Z",
                        "t": 24,
                        "tcc": 3,
                        "tp": 0,
                        "weather": 0,
                        "weather_desc": "Cerah",
                        "weather_desc_en": "Sunny",
                        "wd_deg": 114,
                        "wd": "E",
                        "wd_to": "W",
                        "ws": 2.1,
                        "hu": 90,
                        "vs": 7637,
                        "vs_text": "< 8 km",
                        "time_index": "54-55",
                        "analysis_date": "2026-06-16T12:00:00",
                        "image": "https://api-apps.bmkg.go.id/storage/icon/cuaca/cerah-pm.svg",
                        "utc_datetime": "2026-06-18 19:00:00",
                        "local_datetime": "2026-06-19 02:00:00",
                    },
                    {
                        "datetime": "2026-06-18T22:00:00Z",
                        "t": 23,
                        "tcc": 59,
                        "tp": 0,
                        "weather": 1,
                        "weather_desc": "Cerah",
                        "weather_desc_en": "Sunny",
                        "wd_deg": 202,
                        "wd": "S",
                        "wd_to": "N",
                        "ws": 2.9,
                        "hu": 94,
                        "vs": 7005,
                        "vs_text": "< 8 km",
                        "time_index": "57-58",
                        "analysis_date": "2026-06-16T12:00:00",
                        "image": "https://api-apps.bmkg.go.id/storage/icon/cuaca/cerah-pm.svg",
                        "utc_datetime": "2026-06-18 22:00:00",
                        "local_datetime": "2026-06-19 05:00:00",
                    },
                ],
            ],
        }
    ],
}


MOCKED_FORECAST_WITH_ALL_MALFORED_DATA: dict[str, Any] = {
    "lokasi": {
        "adm1": "32",
        "adm2": "32.16",
        "adm3": "32.16.20",
        "adm4": "32.16.20.2003",
        "provinsi": "Jawa Barat",
        "kotkab": "Bekasi",
        "kecamatan": "Cikarang Pusat",
        "desa": "Pasiranji",
        "lon": 107.2025067024,
        "lat": -6.374008913,
        "timezone": "Asia/Jakarta",
    },
    "data": [
        {
            "lokasi": {
                "adm1": "32",
                "adm2": "32.16",
                "adm3": "32.16.20",
                "adm4": "32.16.20.2003",
                "provinsi": "Jawa Barat",
                "kotkab": "Bekasi",
                "kecamatan": "Cikarang Pusat",
                "desa": "Pasiranji",
                "lon": 107.2025067024,
                "lat": -6.374008913,
                "timezone": "+0700",
                "type": "adm4",
            },
            "cuaca": [
                [
                    {
                        "datetime": "2026-06-16T19:00:00Z",
                        "t": 25,
                        "tcc": "malformed",  # <- malformed, should be int
                        "tp": 0,
                        "weather": 3,
                        "weather_desc": "Berawan",
                        "weather_desc_en": "Mostly Cloudy",
                        "wd_deg": 138,
                        "wd": "SE",
                        "wd_to": "NW",
                        "ws": 4.7,
                        "hu": 91,
                        "vs": 7360,
                        "vs_text": "< 8 km",
                        "time_index": "6-7",
                        "analysis_date": "2026-06-16T12:00:00",
                        "image": "https://api-apps.bmkg.go.id/storage/icon/cuaca/berawan-pm.svg",
                        "utc_datetime": "2026-06-16 19:00:00",
                        "local_datetime": "2026-06-17 02:00:00",
                    },
                    {
                        "datetime": "2026-06-16T22:00:00Z",
                        "t": 24,
                        "tcc": "malformed",  # <- malformed, should be int
                        "tp": 0,
                        "weather": 3,
                        "weather_desc": "Berawan",
                        "weather_desc_en": "Mostly Cloudy",
                        "wd_deg": 154,
                        "wd": "SE",
                        "wd_to": "NW",
                        "ws": 5.2,
                        "hu": 93,
                        "vs": 7008,
                        "vs_text": "< 8 km",
                        "time_index": "9-10",
                        "analysis_date": "2026-06-16T12:00:00",
                        "image": "https://api-apps.bmkg.go.id/storage/icon/cuaca/berawan-pm.svg",
                        "utc_datetime": "2026-06-16 22:00:00",
                        "local_datetime": "2026-06-17 05:00:00",
                    },
                    {
                        "datetime": "2026-06-17T01:00:00Z",
                        "t": 29,
                        "tcc": "malformed",  # <- malformed, should be int
                        "tp": 0,
                        "weather": 0,
                        "weather_desc": "Cerah",
                        "weather_desc_en": "Sunny",
                        "wd_deg": 84,
                        "wd": "NE",
                        "wd_to": "SW",
                        "ws": 7.1,
                        "hu": 67,
                        "vs": 7946,
                        "vs_text": "< 8 km",
                        "time_index": "12-13",
                        "analysis_date": "2026-06-16T12:00:00",
                        "image": "https://api-apps.bmkg.go.id/storage/icon/cuaca/cerah-am.svg",
                        "utc_datetime": "2026-06-17 01:00:00",
                        "local_datetime": "2026-06-17 08:00:00",
                    },
                    {
                        "datetime": "2026-06-17T04:00:00Z",
                        "t": 32,
                        "tcc": "malformed",  # <- malformed, should be int
                        "tp": 0,
                        "weather": 1,
                        "weather_desc": "Cerah",
                        "weather_desc_en": "Sunny",
                        "wd_deg": 74,
                        "wd": "NE",
                        "wd_to": "SW",
                        "ws": 11.5,
                        "hu": 53,
                        "vs": 8001,
                        "vs_text": "< 9 km",
                        "time_index": "15-16",
                        "analysis_date": "2026-06-16T12:00:00",
                        "image": "https://api-apps.bmkg.go.id/storage/icon/cuaca/cerah-am.svg",
                        "utc_datetime": "2026-06-17 04:00:00",
                        "local_datetime": "2026-06-17 11:00:00",
                    },
                    {
                        "datetime": "2026-06-17T07:00:00Z",
                        "t": 33,
                        "tcc": "malformed",  # <- malformed, should be int
                        "tp": 0,
                        "weather": 1,
                        "weather_desc": "Cerah",
                        "weather_desc_en": "Sunny",
                        "wd_deg": 77,
                        "wd": "NE",
                        "wd_to": "SW",
                        "ws": 8.9,
                        "hu": 51,
                        "vs": 8008,
                        "vs_text": "< 9 km",
                        "time_index": "18-19",
                        "analysis_date": "2026-06-16T12:00:00",
                        "image": "https://api-apps.bmkg.go.id/storage/icon/cuaca/cerah-am.svg",
                        "utc_datetime": "2026-06-17 07:00:00",
                        "local_datetime": "2026-06-17 14:00:00",
                    },
                    {
                        "datetime": "2026-06-17T10:00:00Z",
                        "t": 29,
                        "tcc": "malformed",  # <- malformed, should be int
                        "tp": 0.1,
                        "weather": 1,
                        "weather_desc": "Cerah",
                        "weather_desc_en": "Sunny",
                        "wd_deg": 30,
                        "wd": "N",
                        "wd_to": "S",
                        "ws": 6.2,
                        "hu": 71,
                        "vs": 7997,
                        "vs_text": "< 8 km",
                        "time_index": "21-22",
                        "analysis_date": "2026-06-16T12:00:00",
                        "image": "https://api-apps.bmkg.go.id/storage/icon/cuaca/cerah-am.svg",
                        "utc_datetime": "2026-06-17 10:00:00",
                        "local_datetime": "2026-06-17 17:00:00",
                    },
                    {
                        "datetime": "2026-06-17T13:00:00Z",
                        "t": 27,
                        "tcc": "malformed",  # <- malformed, should be int
                        "tp": 0,
                        "weather": 2,
                        "weather_desc": "Cerah Berawan",
                        "weather_desc_en": "Partly Cloudy",
                        "wd_deg": 210,
                        "wd": "S",
                        "wd_to": "N",
                        "ws": 3.9,
                        "hu": 84,
                        "vs": 8011,
                        "vs_text": "< 9 km",
                        "time_index": "24-25",
                        "analysis_date": "2026-06-16T12:00:00",
                        "image": "https://api-apps.bmkg.go.id/storage/icon/cuaca/cerah berawan-pm.svg",
                        "utc_datetime": "2026-06-17 13:00:00",
                        "local_datetime": "2026-06-17 20:00:00",
                    },
                    {
                        "datetime": "2026-06-17T16:00:00Z",
                        "t": 25,
                        "tcc": "malformed",  # <- malformed, should be int
                        "tp": 0,
                        "weather": 1,
                        "weather_desc": "Cerah",
                        "weather_desc_en": "Sunny",
                        "wd_deg": 169,
                        "wd": "SE",
                        "wd_to": "NW",
                        "ws": 3,
                        "hu": 91,
                        "vs": 6986,
                        "vs_text": "< 7 km",
                        "time_index": "27-28",
                        "analysis_date": "2026-06-16T12:00:00",
                        "image": "https://api-apps.bmkg.go.id/storage/icon/cuaca/cerah-pm.svg",
                        "utc_datetime": "2026-06-17 16:00:00",
                        "local_datetime": "2026-06-17 23:00:00",
                    },
                ],
                [
                    {
                        "datetime": "2026-06-17T19:00:00Z",
                        "t": 24,
                        "tcc": "malformed",  # <- malformed, should be int
                        "tp": 0,
                        "weather": 1,
                        "weather_desc": "Cerah",
                        "weather_desc_en": "Sunny",
                        "wd_deg": 169,
                        "wd": "SE",
                        "wd_to": "NW",
                        "ws": 3,
                        "hu": 94,
                        "vs": 6995,
                        "vs_text": "< 7 km",
                        "time_index": "30-31",
                        "analysis_date": "2026-06-16T12:00:00",
                        "image": "https://api-apps.bmkg.go.id/storage/icon/cuaca/cerah-pm.svg",
                        "utc_datetime": "2026-06-17 19:00:00",
                        "local_datetime": "2026-06-18 02:00:00",
                    },
                    {
                        "datetime": "2026-06-17T22:00:00Z",
                        "t": 23,
                        "tcc": "malformed",  # <- malformed, should be int
                        "tp": 0,
                        "weather": 1,
                        "weather_desc": "Cerah",
                        "weather_desc_en": "Sunny",
                        "wd_deg": 158,
                        "wd": "SE",
                        "wd_to": "NW",
                        "ws": 4.8,
                        "hu": 94,
                        "vs": 7010,
                        "vs_text": "< 8 km",
                        "time_index": "33-34",
                        "analysis_date": "2026-06-16T12:00:00",
                        "image": "https://api-apps.bmkg.go.id/storage/icon/cuaca/cerah-pm.svg",
                        "utc_datetime": "2026-06-17 22:00:00",
                        "local_datetime": "2026-06-18 05:00:00",
                    },
                    {
                        "datetime": "2026-06-18T01:00:00Z",
                        "t": 29,
                        "tcc": "malformed",  # <- malformed, should be int
                        "tp": 0,
                        "weather": 1,
                        "weather_desc": "Cerah",
                        "weather_desc_en": "Sunny",
                        "wd_deg": 100,
                        "wd": "E",
                        "wd_to": "W",
                        "ws": 5.6,
                        "hu": 66,
                        "vs": 7987,
                        "vs_text": "< 8 km",
                        "time_index": "36-37",
                        "analysis_date": "2026-06-16T12:00:00",
                        "image": "https://api-apps.bmkg.go.id/storage/icon/cuaca/cerah-am.svg",
                        "utc_datetime": "2026-06-18 01:00:00",
                        "local_datetime": "2026-06-18 08:00:00",
                    },
                    {
                        "datetime": "2026-06-18T04:00:00Z",
                        "t": 32,
                        "tcc": "malformed",  # <- malformed, should be int
                        "tp": 0,
                        "weather": 1,
                        "weather_desc": "Cerah",
                        "weather_desc_en": "Sunny",
                        "wd_deg": 64,
                        "wd": "NE",
                        "wd_to": "SW",
                        "ws": 10.2,
                        "hu": 51,
                        "vs": 8012,
                        "vs_text": "< 9 km",
                        "time_index": "39-40",
                        "analysis_date": "2026-06-16T12:00:00",
                        "image": "https://api-apps.bmkg.go.id/storage/icon/cuaca/cerah-am.svg",
                        "utc_datetime": "2026-06-18 04:00:00",
                        "local_datetime": "2026-06-18 11:00:00",
                    },
                    {
                        "datetime": "2026-06-18T07:00:00Z",
                        "t": 33,
                        "tcc": "malformed",  # <- malformed, should be int
                        "tp": 0,
                        "weather": 1,
                        "weather_desc": "Cerah",
                        "weather_desc_en": "Sunny",
                        "wd_deg": 63,
                        "wd": "NE",
                        "wd_to": "SW",
                        "ws": 10.2,
                        "hu": 48,
                        "vs": 7988,
                        "vs_text": "< 8 km",
                        "time_index": "42-43",
                        "analysis_date": "2026-06-16T12:00:00",
                        "image": "https://api-apps.bmkg.go.id/storage/icon/cuaca/cerah-am.svg",
                        "utc_datetime": "2026-06-18 07:00:00",
                        "local_datetime": "2026-06-18 14:00:00",
                    },
                    {
                        "datetime": "2026-06-18T10:00:00Z",
                        "t": 29,
                        "tcc": "malformed",  # <- malformed, should be int
                        "tp": 0,
                        "weather": 0,
                        "weather_desc": "Cerah",
                        "weather_desc_en": "Sunny",
                        "wd_deg": 67,
                        "wd": "NE",
                        "wd_to": "SW",
                        "ws": 10.2,
                        "hu": 67,
                        "vs": 8011,
                        "vs_text": "< 9 km",
                        "time_index": "45-46",
                        "analysis_date": "2026-06-16T12:00:00",
                        "image": "https://api-apps.bmkg.go.id/storage/icon/cuaca/cerah-am.svg",
                        "utc_datetime": "2026-06-18 10:00:00",
                        "local_datetime": "2026-06-18 17:00:00",
                    },
                    {
                        "datetime": "2026-06-18T13:00:00Z",
                        "t": 27,
                        "tcc": "malformed",  # <- malformed, should be int
                        "tp": 0,
                        "weather": 1,
                        "weather_desc": "Cerah",
                        "weather_desc_en": "Sunny",
                        "wd_deg": 122,
                        "wd": "E",
                        "wd_to": "W",
                        "ws": 4.7,
                        "hu": 81,
                        "vs": 7989,
                        "vs_text": "< 8 km",
                        "time_index": "48-49",
                        "analysis_date": "2026-06-16T12:00:00",
                        "image": "https://api-apps.bmkg.go.id/storage/icon/cuaca/cerah-pm.svg",
                        "utc_datetime": "2026-06-18 13:00:00",
                        "local_datetime": "2026-06-18 20:00:00",
                    },
                    {
                        "datetime": "2026-06-18T16:00:00Z",
                        "t": 26,
                        "tcc": "malformed",  # <- malformed, should be int
                        "tp": 0,
                        "weather": 0,
                        "weather_desc": "Cerah",
                        "weather_desc_en": "Sunny",
                        "wd_deg": 148,
                        "wd": "SE",
                        "wd_to": "NW",
                        "ws": 4,
                        "hu": 86,
                        "vs": 8002,
                        "vs_text": "< 9 km",
                        "time_index": "51-52",
                        "analysis_date": "2026-06-16T12:00:00",
                        "image": "https://api-apps.bmkg.go.id/storage/icon/cuaca/cerah-pm.svg",
                        "utc_datetime": "2026-06-18 16:00:00",
                        "local_datetime": "2026-06-18 23:00:00",
                    },
                ],
                [
                    {
                        "datetime": "2026-06-18T19:00:00Z",
                        "t": 24,
                        "tcc": "malformed",  # <- malformed, should be int
                        "tp": 0,
                        "weather": 0,
                        "weather_desc": "Cerah",
                        "weather_desc_en": "Sunny",
                        "wd_deg": 114,
                        "wd": "E",
                        "wd_to": "W",
                        "ws": 2.1,
                        "hu": 90,
                        "vs": 7637,
                        "vs_text": "< 8 km",
                        "time_index": "54-55",
                        "analysis_date": "2026-06-16T12:00:00",
                        "image": "https://api-apps.bmkg.go.id/storage/icon/cuaca/cerah-pm.svg",
                        "utc_datetime": "2026-06-18 19:00:00",
                        "local_datetime": "2026-06-19 02:00:00",
                    },
                    {
                        "datetime": "2026-06-18T22:00:00Z",
                        "t": 23,
                        "tcc": "malformed",  # <- malformed, should be int
                        "tp": 0,
                        "weather": 1,
                        "weather_desc": "Cerah",
                        "weather_desc_en": "Sunny",
                        "wd_deg": 202,
                        "wd": "S",
                        "wd_to": "N",
                        "ws": 2.9,
                        "hu": 94,
                        "vs": 7005,
                        "vs_text": "< 8 km",
                        "time_index": "57-58",
                        "analysis_date": "2026-06-16T12:00:00",
                        "image": "https://api-apps.bmkg.go.id/storage/icon/cuaca/cerah-pm.svg",
                        "utc_datetime": "2026-06-18 22:00:00",
                        "local_datetime": "2026-06-19 05:00:00",
                    },
                ],
            ],
        }
    ],
}


MOCKED_FLATTENED_FORECAST_DATA: list[dict[str, Any]] = [
    {
        "datetime": "2026-06-16T19:00:00Z",
        "t": 25,
        "tcc": 98,
        "tp": 0,
        "weather": 3,
        "weather_desc": "Berawan",
        "weather_desc_en": "Mostly Cloudy",
        "wd_deg": 138,
        "wd": "SE",
        "wd_to": "NW",
        "ws": 4.7,
        "hu": 91,
        "vs": 7360,
        "vs_text": "< 8 km",
        "time_index": "6-7",
        "analysis_date": "2026-06-16T12:00:00",
        "image": "https://api-apps.bmkg.go.id/storage/icon/cuaca/berawan-pm.svg",
        "utc_datetime": "2026-06-16 19:00:00",
        "local_datetime": "2026-06-17 02:00:00",
    },
    {
        "datetime": "2026-06-16T22:00:00Z",
        "t": 24,
        "tcc": 96,
        "tp": 0,
        "weather": 3,
        "weather_desc": "Berawan",
        "weather_desc_en": "Mostly Cloudy",
        "wd_deg": 154,
        "wd": "SE",
        "wd_to": "NW",
        "ws": 5.2,
        "hu": 93,
        "vs": 7008,
        "vs_text": "< 8 km",
        "time_index": "9-10",
        "analysis_date": "2026-06-16T12:00:00",
        "image": "https://api-apps.bmkg.go.id/storage/icon/cuaca/berawan-pm.svg",
        "utc_datetime": "2026-06-16 22:00:00",
        "local_datetime": "2026-06-17 05:00:00",
    },
    {
        "datetime": "2026-06-17T01:00:00Z",
        "t": 29,
        "tcc": 1,
        "tp": 0,
        "weather": 0,
        "weather_desc": "Cerah",
        "weather_desc_en": "Sunny",
        "wd_deg": 84,
        "wd": "NE",
        "wd_to": "SW",
        "ws": 7.1,
        "hu": 67,
        "vs": 7946,
        "vs_text": "< 8 km",
        "time_index": "12-13",
        "analysis_date": "2026-06-16T12:00:00",
        "image": "https://api-apps.bmkg.go.id/storage/icon/cuaca/cerah-am.svg",
        "utc_datetime": "2026-06-17 01:00:00",
        "local_datetime": "2026-06-17 08:00:00",
    },
    {
        "datetime": "2026-06-17T04:00:00Z",
        "t": 32,
        "tcc": 21,
        "tp": 0,
        "weather": 1,
        "weather_desc": "Cerah",
        "weather_desc_en": "Sunny",
        "wd_deg": 74,
        "wd": "NE",
        "wd_to": "SW",
        "ws": 11.5,
        "hu": 53,
        "vs": 8001,
        "vs_text": "< 9 km",
        "time_index": "15-16",
        "analysis_date": "2026-06-16T12:00:00",
        "image": "https://api-apps.bmkg.go.id/storage/icon/cuaca/cerah-am.svg",
        "utc_datetime": "2026-06-17 04:00:00",
        "local_datetime": "2026-06-17 11:00:00",
    },
    {
        "datetime": "2026-06-17T07:00:00Z",
        "t": 33,
        "tcc": 24,
        "tp": 0,
        "weather": 1,
        "weather_desc": "Cerah",
        "weather_desc_en": "Sunny",
        "wd_deg": 77,
        "wd": "NE",
        "wd_to": "SW",
        "ws": 8.9,
        "hu": 51,
        "vs": 8008,
        "vs_text": "< 9 km",
        "time_index": "18-19",
        "analysis_date": "2026-06-16T12:00:00",
        "image": "https://api-apps.bmkg.go.id/storage/icon/cuaca/cerah-am.svg",
        "utc_datetime": "2026-06-17 07:00:00",
        "local_datetime": "2026-06-17 14:00:00",
    },
    {
        "datetime": "2026-06-17T10:00:00Z",
        "t": 29,
        "tcc": 36,
        "tp": 0.1,
        "weather": 1,
        "weather_desc": "Cerah",
        "weather_desc_en": "Sunny",
        "wd_deg": 30,
        "wd": "N",
        "wd_to": "S",
        "ws": 6.2,
        "hu": 71,
        "vs": 7997,
        "vs_text": "< 8 km",
        "time_index": "21-22",
        "analysis_date": "2026-06-16T12:00:00",
        "image": "https://api-apps.bmkg.go.id/storage/icon/cuaca/cerah-am.svg",
        "utc_datetime": "2026-06-17 10:00:00",
        "local_datetime": "2026-06-17 17:00:00",
    },
    {
        "datetime": "2026-06-17T13:00:00Z",
        "t": 27,
        "tcc": 72,
        "tp": 0,
        "weather": 2,
        "weather_desc": "Cerah Berawan",
        "weather_desc_en": "Partly Cloudy",
        "wd_deg": 210,
        "wd": "S",
        "wd_to": "N",
        "ws": 3.9,
        "hu": 84,
        "vs": 8011,
        "vs_text": "< 9 km",
        "time_index": "24-25",
        "analysis_date": "2026-06-16T12:00:00",
        "image": "https://api-apps.bmkg.go.id/storage/icon/cuaca/cerah berawan-pm.svg",
        "utc_datetime": "2026-06-17 13:00:00",
        "local_datetime": "2026-06-17 20:00:00",
    },
    {
        "datetime": "2026-06-17T16:00:00Z",
        "t": 25,
        "tcc": 27,
        "tp": 0,
        "weather": 1,
        "weather_desc": "Cerah",
        "weather_desc_en": "Sunny",
        "wd_deg": 169,
        "wd": "SE",
        "wd_to": "NW",
        "ws": 3,
        "hu": 91,
        "vs": 6986,
        "vs_text": "< 7 km",
        "time_index": "27-28",
        "analysis_date": "2026-06-16T12:00:00",
        "image": "https://api-apps.bmkg.go.id/storage/icon/cuaca/cerah-pm.svg",
        "utc_datetime": "2026-06-17 16:00:00",
        "local_datetime": "2026-06-17 23:00:00",
    },
]


MOCKED_FORECAST_LOCATION_DATA: dict[str, Any] = {
    "adm1": "32",
    "adm2": "32.16",
    "adm3": "32.16.20",
    "adm4": "32.16.20.2003",
    "provinsi": "Jawa Barat",
    "kotkab": "Bekasi",
    "kecamatan": "Cikarang Pusat",
    "desa": "Pasiranji",
    "lon": 107.2025067024,
    "lat": -6.374008913,
    "timezone": "+0700",
    "type": "adm4",
}
